##Bag Of Word

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text":['people watching t20 worldcup', 
                          'bishwa watching ipl',
                          "people comment in my profile",
                          "bishwa reply the comment"], "output":[1,1,0,0]})

In [4]:
df

text  output
0  people watching t20 worldcup       1
1           bishwa watching ipl       1
2  people comment in my profile       0
3      bishwa reply the comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people': 5, 'watching': 10, 't20': 8, 'worldcup': 11, 'bishwa': 0, 'ipl': 3, 'comment': 1, 'in': 2, 'my': 4, 'profile': 6, 'reply': 7, 'the': 9}


In [8]:
print(bow[0].toarray())

[[0 0 0 0 0 1 0 0 1 0 1 1]]


In [9]:
print(bow[1].toarray())

[[1 0 0 1 0 0 0 0 0 0 1 0]]


##n-gram

In [10]:
cv = CountVectorizer(ngram_range=(2,2))

In [11]:
bow = cv.fit_transform(df.text)

In [12]:
print(cv.vocabulary_)

{'people watching': 6, 'watching t20': 11, 't20 worldcup': 8, 'bishwa watching': 1, 'watching ipl': 10, 'people comment': 5, 'comment in': 2, 'in my': 3, 'my profile': 4, 'bishwa reply': 0, 'reply the': 7, 'the comment': 9}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 0 0 1 0 1 0 0 1]]
[[0 1 0 0 0 0 0 0 0 0 1 0]]
[[0 0 1 1 1 1 0 0 0 0 0 0]]


## TF-IDF(Term Frequency - Inverse Document Frequency

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer()

In [20]:
tfidf = tfidfv.fit_transform(df.text)

In [21]:
print(tfidfv.vocabulary_)

{'people': 5, 'watching': 10, 't20': 8, 'worldcup': 11, 'bishwa': 0, 'ipl': 3, 'comment': 1, 'in': 2, 'my': 4, 'profile': 6, 'reply': 7, 'the': 9}


In [23]:
print(tfidf[0].toarray())
print(tfidf[1].toarray())
print(tfidf[2].toarray())

[[0.         0.         0.         0.         0.         0.43779123
  0.         0.         0.55528266 0.         0.43779123 0.55528266]]
[[0.52640543 0.         0.         0.66767854 0.         0.
  0.         0.         0.         0.         0.52640543 0.        ]]
[[0.         0.38274272 0.48546061 0.         0.48546061 0.38274272
  0.48546061 0.         0.         0.         0.         0.        ]]


In [24]:
print(tfidfv.idf_)

[1.51082562 1.51082562 1.91629073 1.91629073 1.91629073 1.51082562
 1.91629073 1.91629073 1.91629073 1.91629073 1.51082562 1.91629073]


In [26]:
print(tfidfv.get_feature_names())

['bishwa', 'comment', 'in', 'ipl', 'my', 'people', 'profile', 'reply', 't20', 'the', 'watching', 'worldcup']


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
